---
- name: Update apt packages
  hosts: all
  become: yes
  vars:
    # Set to true to upgrade installed packages
    upgrade_packages: false
    
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      register: apt_update_result

    - name: Display update results
      ansible.builtin.debug:
        msg: "APT cache updated successfully"

    - name: Upgrade all packages (optional)
      ansible.builtin.apt:
        upgrade: full
        autoclean: yes
        autoremove: yes
      when: upgrade_packages | bool
      register: apt_upgrade_result

    - name: Display upgrade results
      ansible.builtin.debug:
        msg: "Packages upgraded successfully"
      when: upgrade_packages | bool
